### ISSUE TITLE
allow disabling default regexp

### ISSUE THREAD

**Issue by jacob-keller** [Morantron/tmux-fingers#19]
Is it possible to disable the default search parameters? I don't really need number searching, and I don't really find the path searching that useful since it gets a lot of false positives. Thus, these hints clutter the display making it harder to locate the things I want to copy.

**Comment by Morantron** [comment]
In the current version is not possible to disable default patterns, but that's a good point.

It could be fixed by conditionally adding patterns to the `PATTERN_LIST` array [here](https://github.com/Morantron/tmux-fingers/blob/d4f086de291ed6dc5759540675179453b5b62b75/scripts/config.sh#L26).

To enable this, a new variable `@fingers-enabled-default-patterns` could be set to comma separated names of patterns. ex: `shas,digits,ips`

PR welcome! \o/

**Comment by aspiers** [comment]
I agree that this would be a useful modification.  Also even without disabling default patterns, I think the user ones should take precedence.  Currently it seems they are matched _after_ the built-ins.

**Comment by quite** [comment]
@Morantron sounds like you'd then have to give clear, understandable names to the default patterns? Might be tricky to do it well. We could go for adding just a way to disable the default patterns? Since the user anyway is about to customize their own... Like `@fingers-disable-default-patterns` with values `0` (default) or `1`. I could prepare a PR with that.

**Comment by Morantron** [comment]
> @Morantron sounds like you'd then have to give clear, understandable names to the default patterns? Might be tricky to do it well. We could go for adding just a way to disable the default patterns? Since the user anyway is about to customize their own... Like `@fingers-disable-default-patterns` with values `0` (default) or `1`. I could prepare a PR with that.

You are right 🤔 

Regarding the PR, I'm rewriting [the whole thing in ruby](https://github.com/Morantron/tmux-fingers/pull/79). Just need to get my ass to document the changes and release it once and for all.

**Comment by quite** [comment]
Oh, that's somewhat unfortunate for me personally. Bash and gawk is O-K, but I'd not depend on having ruby on my systems for this kind of basic working-environment stuff. I'd have to remain on tmux-fingers in bash. Hohum.

**Comment by Morantron** [comment]
¯\\\_(ツ)\_/¯

**Comment by Morantron** [comment]
Fixed in 2.2.0 (seven years later hehehehehe). Check out [this new option](https://github.com/morantron/tmux-fingers?tab=readme-ov-file#fingers-enabled-builtin-patterns)
